http_docker/kvmvdi/client/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    path('', views.home, name='home'),
    path('/instances', views.instances, name='instances'),
    path('/networks', views.networks, name='networks'),
    path('/snapshots', views.snapshots, name='snapshots'),
    path('/sshkeys', views.sshkeys, name='sshkeys'),
    path('/volumes', views.volumes, name='volumes'),
    path('/show_instances/<str:serverid>', views.show_instances, name='show_instances'),
    path('/profile', views.user_profile, name='profile'),
    path('/oders', views.user_oders, name='oders'),
    path('/logout', views.user_logout, name='logout'),
    path('/home_data_', views.home_data, name='home_data'),

]

http_docker/kvmvdi/kvmvdi/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path(r'', include('superadmin.urls', namespace='superadmin')),
    path(r'client', include('client.urls', namespace='client')),
]

http_docker/kvmvdi/superadmin/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'superadmin'
urlpatterns = [
    path('', views.user_login),
    path('home', views.home, name='home'),
    path('flavors', views.flavors, name='flavors'),
    path('users', views.users, name='users'),

    # url(r'register/$',views.register, name='register'),
    # url(r'login/$', views.user_login, name='login'),

    path('profile/', views.user_profile, name='profile'),
    path('logout/', views.user_logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path(r'^resetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.resetpwd, name='resetpassword'),
    path('home_data_<str:ops_ip>', views.home_data, name='home_data'),

    # url(r'chat/([0-9]{5})',views.chat, name='chat'),
    # url(r'update_status/$', views.update_status, name='update_status'),
    # url(r'edit_contact/([^@]+@[^@]+\.[^@]+)', views.edit_contact, name='edit_contact'),
    # url(r'add_contact/$', views.add_contact, name='add_contact'),
    path('payment', views.payment, name='payment'),
    path('payment_ipn', views.payment_ipn, name='payment_ipn'),
    path('payment_return', views.payment_return, name='payment_return'),
    path('query', views.query, name='query'),
    path('refund', views.refund, name='refund'),
]

http_docker/kvmvdi/superadmin/forms.py
from django import forms
from django.contrib.auth.models import User
from superadmin.models import MyUser
from django.core.validators import validate_email
import binascii, os
from django.contrib.auth.hashers import check_password

def get_user(usname):
    try:
        return MyUser.objects.get(username=usname)
    except:
        return None

def get_user_email(email1):
    try:
        return MyUser.objects.get(email=email1)
    except:
        return None


def get_users_email(email1):
    try:
        return MyUser.objects.get(email=email1)
    except:
        return None

def active(user):
    if user.is_active == False:
        return False
    else:
        return True


def authenticate(username=None, password=None):
	# u = get_user(username)
    if get_user(username):
        u = get_user(username)
        login_valid = (u.username == username)
        pwd_valid = check_password(password, u.password)
        if login_valid and pwd_valid:
            try:
                user = MyUser.objects.get(username=username)
            except:
                return None
            return user
        return None
    else:
        return None

class UserForm(forms.Form):
    fullname = forms.CharField()

    username = forms.CharField()

    email = forms.CharField()

    # phone = forms.RegexField(regex=r'^\+?1?\d{9,15}$', error_messages={"invalid": "số điện thoại không hợp lệ"})

    password = forms.CharField()

    password2 = forms.CharField()

    # check password
    def clean_password2(self):
        if 'password' in self.cleaned_data:
            password = self.cleaned_data['password']
            password2 = self.cleaned_data['password2']
            if password == password2 and password:
                return password2
            else:
                raise forms.ValidationError("Re-password doesn't match!")
        raise forms.ValidationError("Password is invalid!")


    # check xem user name đã tồn tại hay chưa
    def clean_username(self):
        username =  self.cleaned_data['username']
        if get_user(username) is not None:
            raise forms.ValidationError("Username was existed!")
        return username

    # check email có đúng định dạng không, đã tồn tại chưa
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_users_email(email) is not None:
            raise forms.ValidationError("Email was registered!")
        try:
            validate_email(email)
        except:
            raise forms.ValidationError("Email is invalid!")
        return email


    # lưu tài khoản User
    def save(self):
        u = MyUser.objects.create_user(fullname=self.cleaned_data['fullname'], username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password'], key=binascii.hexlify(os.urandom(24)).decode("utf-8"))
        return u


# form reset mật khẩu cho User
class UserResetForm(forms.Form):
    uemail = forms.CharField( )

    # check email xem đã tồn tại chưa, đúng định dạng không
    def clean_uemail(self):
        uemail = self.cleaned_data['uemail']
        try:
            validate_email(uemail)
        except:
            raise forms.ValidationError("Email is invalid")
        if get_users_email(uemail) is None:
            raise forms.ValidationError("Email isn't registered")
        return uemail


# form thay đổi mật khẩu mới khi User bấm vào link xác nhận trong email
class ResetForm(forms.Form):
    pwd1 = forms.CharField(widget=forms.PasswordInput(
        attrs={               
            'class': 'form-control',
        }
    ))

    pwd2 = forms.CharField(widget=forms.PasswordInput(
        attrs={               
            'class': 'form-control',
        }
    ))

    # check mật khẩu 
    def clean(self):
        if 'pwd1' in self.cleaned_data:
            pwd1 = self.cleaned_data['pwd1']
            pwd2 = self.cleaned_data['pwd2']
            if pwd1 == pwd2 and pwd1:
                return pwd1
            else:
                raise forms.ValidationError("Re-password does not match!")
        raise forms.ValidationError("Password is invalid!")


class PaymentForm(forms.Form):

    order_id = forms.CharField(max_length=250)
    order_type = forms.CharField(max_length=20)
    amount = forms.IntegerField()
    order_desc = forms.CharField(max_length=100)
    bank_code = forms.CharField(max_length=20, required=False)
    language = forms.CharField(max_length=2)

http_docker/kvmvdi/superadmin/views.py
import urllib

from django.shortcuts import render, redirect, get_object_or_404
from django.template import RequestContext
from django.contrib.auth import login
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import logout
import uuid
import random

from django.utils import timezone
from django.utils.safestring import mark_safe
import json
from django.contrib.auth.models import User
import threading
from superadmin.forms import UserForm, authenticate, UserResetForm, get_user_email, ResetForm, PaymentForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text

from .tokens import account_activation_token
from django.core.mail import EmailMessage
from superadmin.models import *
import os
from superadmin.vnpay import vnpay

from .plugin.novaclient import nova
from .plugin.keystoneclient import keystone
from .plugin.neutronclient import neutron
from .plugin.get_tokens import getToken
from kvmvdi.settings import OPS_ADMIN, OPS_IP, OPS_PASSWORD, OPS_PROJECT, OPS_TOKEN_EXPIRED, VNPAY_HASH_SECRET_KEY, VNPAY_TMN_CODE, VNPAY_API_URL, VNPAY_PAYMENT_URL, VNPAY_RETURN_URL, \
        PRICE_RAM, PRICE_VCPUS, PRICE_DISK_HDD ,PRICE_DISK_SSD, DISK_HDD, DISK_SSD
from django.utils import timezone

                
class EmailThread(threading.Thread):
    def __init__(self, email):
        threading.Thread.__init__(self)
        self._stop_event = threading.Event()
        self.email = email

    def run(self):
        self.email.send()

class check_ping(threading.Thread):
    def __init__(self, host):
        threading.Thread.__init__(self)
        self._stop_event = threading.Event()
        self.host = host

    def run(self):
        # response = os.system("ping -n 1 " + self.host)
        response = os.system("ping -c 1 " + self.host)
        if response == 0:
            return True
        else:
            return False

def home(request):
    user = request.user
    list_ops = Ops.objects.all()
    if user.is_authenticated  and user.is_adminkvm:
        if request.method == 'POST':
            if 'image' in request.POST:
                if Ops.objects.get(ip=request.POST['ops']):
                    ops = Ops.objects.get(ip=request.POST['ops'])
                    if not user.check_expired():
                        user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                        user.token_id = getToken(ip=ops.ip, username=user.username, password=user.username,
                                                 project_name=user.username, user_domain_id='default',
                                                 project_domain_id='default')
                        user.save()
                    connect = nova(ip=ops.ip, token_id=user.token_id, project_name=user.username,
                                   project_domain_id=ops.projectdomain)

                    svname = request.POST['svname']
                    image = request.POST['image']
                    network = request.POST['network']
                    ram = int(float(request.POST['ram']) * 1024)
                    vcpus = int(request.POST['vcpus'])
                    disk = int(request.POST['disk'])
                    count = int(request.POST['count'])

                    if [ram, vcpus, disk] in connect.list_flavor():
                        fl = connect.find_flavor(ram=ram, vcpus=vcpus, disk=disk)
                        im = connect.find_image(image)
                        net = connect.find_network(network)
                        connect.createVM(svname=svname, flavor=fl, image=im, network_id=net, max_count=count)
                    else:
                        connect.createFlavor(svname=svname, ram=ram, vcpus=vcpus, disk=disk)
                        check = False
                        while check == False:
                            if connect.find_flavor(ram=ram, vcpus=vcpus, disk=disk):
                                check = True
                        connect.createVM(svname=svname, flavor=connect.find_flavor(ram=ram, vcpus=vcpus, disk=disk), image=connect.find_image(image), network_id=connect.find_network(network), max_count=count)
                else:
                    return HttpResponseRedirect('/')
            elif 'delete' in request.POST:
                ops = Ops.objects.get(ip=request.POST['ops'])
                if not user.check_expired():
                    user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                    user.token_id = getToken(ip=ops.ip, username=user.username, password=user.username,
                                             project_name=user.username, user_domain_id='default',
                                             project_domain_id='default')
                    user.save()
                connect = nova(ip=ops.ip, token_id=user.token_id, project_name=user.username,
                               project_domain_id=ops.projectdomain)
                svid = request.POST['delete']
                connect.delete_vm(svid=svid)
            elif 'ipsv' in request.POST:
                Ops.objects.create(name=request.POST['nameops'],
                                    ip=request.POST['ipsv'],
                                    username=request.POST['username'],
                                    password=request.POST['password'],
                                    project=request.POST['project'],
                                    userdomain=request.POST['userid'],
                                    projectdomain=request.POST['projectid'])
            elif 'reload_image' in request.POST:
                ops_ip = request.POST['reload_image']
                if Ops.objects.get(ip=ops_ip):
                    thread = check_ping(host=ops_ip)
                    if thread.run():
                        ops = Ops.objects.get(ip=ops_ip)
                        if not user.check_expired():
                            user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                            user.token_id = getToken(ip=ops.ip, username=user.username, password=user.username,
                                                    project_name=user.username, user_domain_id='default',
                                                    project_domain_id='default')
                            user.save()
                        connect = nova(ip=ops.ip, token_id=user.token_id, project_name=user.username,
                                    project_domain_id=ops.projectdomain)
                        try:
                            Images.objects.all().delete()
                        except:
                            pass
                        im = connect.list_Images()
                        while True:
                            try:
                                image = im.__next__()
                                if image['visibility'] == 'public':
                                    try:
                                        Images.objects.create(ops=ops, name=image['name'], os=image['os_type'], i_d=image.id)
                                    except:
                                        Images.objects.create(ops=ops, name=image['name'], os='other', i_d=image.id)
                            except StopIteration:
                                break
                        
        return render(request, 'kvmvdi/index.html',{'username': mark_safe(json.dumps(user.username)),
                                                        'ops': list_ops,
                                                        'OPS_IP': OPS_IP
                                                        })
    else:
        return HttpResponseRedirect('/')

def flavors(request):
    user = request.user
    list_ops = Ops.objects.all()
    ops = Ops.objects.get(ip=OPS_IP)
    if user.is_authenticated  and user.is_adminkvm:
        if request.method == 'POST':
            if 'ram' in request.POST:
                if user.token_id is None or user.check_expired() == False:
                    user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                    user.token_id = getToken(ip=OPS_IP, username=OPS_ADMIN, password=OPS_PASSWORD, project_name=OPS_PROJECT,
                                user_domain_id='default', project_domain_id='default')
                    user.save()
                connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=OPS_PROJECT,
                            project_domain_id='default')
                flavor = connect.createFlavor(svname=request.POST['flavorname'], ram=int(request.POST['ram'])*1024, vcpus=int(request.POST['vcpus']), disk=0)
                Flavors.objects.create(ops=ops, i_d=flavor.id ,ram=int(request.POST['ram']), vcpus=int(request.POST['vcpus']), disk=int(request.POST['disk']), name=request.POST['flavorname'])
            elif 'flavorid' in request.POST:
                if user.token_id is None or user.check_expired() == False:
                    user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                    user.token_id = getToken(ip=OPS_IP, username=OPS_ADMIN, password=OPS_PASSWORD, project_name=OPS_PROJECT,
                                user_domain_id='default', project_domain_id='default')
                    user.save()
                connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=OPS_PROJECT,
                            project_domain_id='default')
                try:
                    fl = Flavors.objects.get(id=request.POST['flavorid'])
                    connect.deleteFlavor(i_d=fl.i_d)
                    fl.delete()
                except:

http_docker/kvmvdi/superadmin/templates/kvmvdi/acc_active_email.html
{% autoescape off %}
Xin chào {{ user.username }},
Click vào đường dẫn bên dưới để kích hoạt tài khoản của bạn,
https://{{ domain }}{% url 'superadmin:activate' uidb64=uid token=token %}
{% endautoescape %}

http_docker/kvmvdi/superadmin/templates/kvmvdi/flavors.html
{% extends 'kvmvdi/base.html' %}
{% load static %}
{% block title %}Quản lý Flavors{% endblock %}
{% block js %}  
{% endblock%}
{% block content %}
    
        <!-- Start Page Content -->
        <div class="row">
            
            <!-- /# column -->
            <div class="col-lg-12" id="info_user">
                <div class="card">
                    <div class="card-title">
                        <h4>Quản lý Flavors</h4>
                    </div>
                    {% csrf_token %}
                    <div class="card-body">
                        <table id="list_flavors" class="display nowrap table table-hover table-striped table-bordered list_flavor_client" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Ram (GB)</th>
                                    <th>VCPUs</th>
                                    <th>Disk</th>
                                    <th>Actives</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for fl in flavors %}
                                <tr>
                                    <td>{{fl.name}}</td>
                                    <td>{{fl.ram}}</td>
                                    <td>{{fl.vcpus}}</td>
                                    <td>{{fl.disk}}</td>
                                    <td>
                                        <button type="button" class="btn btn-danger delete_flavor" id="{{fl.id}}"data-toggle="tooltip" title="xóa">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor%}
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
       </div>     
<!-- End Container fluid  -->
<!-- footer -->
<!-- End footer -->
</div>

<script src="{% static 'js/base-js/datatables.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.all.min.js"></script>
<script src="{% static 'js/superadmin/flavors.js' %}"></script>
{% endblock%}

http_docker/kvmvdi/superadmin/templates/kvmvdi/formresetpass.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Reset Password</title>
</head>
<body>
    <br/>
    <br/>
    <div class="container" id="id04">
        <div class="panel panel-info">
            <div class="panel-heading">
                Reset password
            </div>
            <div class="panel-body">
                <form action="" method="POST" onsubmit="return validate()">
                    {% csrf_token %}
                    <label for="pwd1"><b>New password</b></label>
                    <input type="password" class="form-control" id="pwd1" name="pwd1" required>
                    <div class="invalid-msg" id="invalid-msg1"></div><br>

                    <label for="pwd2"><b>Retype </b></label>
                    <input type="password" class="form-control"id="pwd2" name="pwd2" required>
                    <div class="invalid-msg" id="invalid-msg2"></div><br/>
                    <button type="submit" class="btn btn-primary" value="OK" id="uemail" >Change</button>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    function validate(){
        $('#invalid-msg1').html('');
        $('#invalid-msg2').html('');
        if($('#pwd1').val() != $('#pwd2').val() ){
            $('#invalid-msg2').html('<em>re-password is in correct</em>').css('color','red');
            return false;
        }
        return true;
    }
</script>
</body>
</html>

http_docker/kvmvdi/superadmin/templates/kvmvdi/index.html
{% extends "kvmvdi/base.html" %}
{% load staticfiles %}
{% block content %}
		{% if user.is_authenticated %}

        {% for ops in ops%}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-title">
                            <h4>VMs list in OpenStack system: <b>{{ops.name}} - {{ops.ip}}</b></h4><br>
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-title="{{ops.ip}}" data-target="#id02">
                                <i class="fa fa-plus"></i> Create VMs
                            </button>

                            <button type="button" class="btn btn-danger update_image" data-ops="{{OPS_IP}}">
                                <i class="fa fa-refreshs"></i> Update Image
                            </button>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="display nowrap table table-hover table-striped table-bordered list_vm" name="{{ops.ip}}" id="list_vm_{{ops.ip}}" width="100%">
                                    <thead>
                                        <tr align="center">
                                            <th>Host</th>
                                            <th>Name</th>
                                            {% comment %} <th>Image Name</th> {% endcomment %}
                                            <th>IP Address</th>
                                            {% comment %} <th>Network</th> {% endcomment %}
                                            {% comment %} <th>Flavor</th> {% endcomment %}
                                            <th>Status</th>
                                            <th>Time since created</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody align="center">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor%}
        

        <div class="row">
          <div class="col-lg-4">
              <div class="card">
                <div class="card-body">
                  <div class="year-calendar"></div>
                </div>
              </div>
          </div>

          <div class="col-lg-8">
                <div class="card">
                    <div class="card-title">
                        <h4>Lịch sử </h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th width="10%">ID</th>
                                        <th width="35%">Tiêu đề</th>
                                        <th width="20%">Chủ đề</th>
                                        <th width="10%">Người gửi</th>
                                        <th width="10%">Trạng thái</th>
                                        <th width="15%">Ngày hết hạn</th>
                                    </tr>
                                </thead>

                                <tbody id="list_tk_h istory">

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
          </div>

        </div>

		{% endif %}
{% endblock content %}

{% block js %}
    <script src="{% static 'js/superadmin/home_superadmin.js' %}"></script>
{% endblock %}

http_docker/kvmvdi/superadmin/templates/kvmvdi/resetpwd.html
{% autoescape off %}
Hello {{ user.fullname }},
Click vào đường dẫn bên dưới để cập nhật lại mật khẩu,
http://{{ domain }}{% url 'superadmin:resetpassword' uidb64=uid token=token %}
{% endautoescape %}

http_docker/kvmvdi/superadmin/templates/kvmvdi/user.html
{% extends 'kvmvdi/base.html' %}
{% load static %}
{% block title %}Quản lý Flavors{% endblock %}
{% block js %}  
{% endblock%}
{% block content %}
    
        <!-- Start Page Content -->
        <div class="row">
            
            <!-- /# column -->
            <div class="col-lg-12" id="info_user">
                <div class="card">
                    <div class="card-title">
                        <h4>Quản lý Users</h4>
                    </div>
                    {% csrf_token %}
                    <div class="card-body">
                        <table class="display nowrap table table-hover table-striped table-bordered list_user_client" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Fullname</th>
                                    <th>Username</th>
                                    <th>Status</th>
                                    <th>Money</th>
                                    <th>Actives</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                    <tr>
                                        <td>{{user.fullname}}</td>
                                        <td>{{user.username}}</td>
                                        {% if user.is_active == 1 %}
                                            <td>Active</td>
                                        {% else %}
                                            <td>Block</td>
                                        {% endif%}
                                        <td>{{user.money}}</td>
                                        <td>
                                            <button type="button" class="btn btn-danger delete_user" id="{{user.id}}"data-toggle="tooltip" title="xóa">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
       </div>     
<!-- End Container fluid  -->
<!-- footer -->
<!-- End footer -->
</div>

<script src="{% static 'js/base-js/datatables.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.all.min.js"></script>
<script src="{% static 'js/superadmin/users.js' %}"></script>
{% endblock%}