http_docker/kvmvdi/client/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'client'
urlpatterns = [
    path('', views.home, name='home'),
    path('/instances', views.instances, name='instances'),
    path('/networks', views.networks, name='networks'),
    path('/snapshots', views.snapshots, name='snapshots'),
    path('/sshkeys', views.sshkeys, name='sshkeys'),
    path('/volumes', views.volumes, name='volumes'),
    path('/show_instances/<str:serverid>', views.show_instances, name='show_instances'),
    path('/profile', views.user_profile, name='profile'),
    path('/oders', views.user_oders, name='oders'),
    path('/logout', views.user_logout, name='logout'),
    path('/home_data_', views.home_data, name='home_data'),

]

http_docker/kvmvdi/kvmvdi/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path(r'', include('superadmin.urls', namespace='superadmin')),
    path(r'client', include('client.urls', namespace='client')),
]

http_docker/kvmvdi/superadmin/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'superadmin'
urlpatterns = [
    path('', views.user_login),
    path('home', views.home, name='home'),
    path('flavors', views.flavors, name='flavors'),
    path('users', views.users, name='users'),

    # url(r'register/$',views.register, name='register'),
    # url(r'login/$', views.user_login, name='login'),

    path('profile/', views.user_profile, name='profile'),
    path('logout/', views.user_logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path(r'^resetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.resetpwd, name='resetpassword'),
    path('home_data_<str:ops_ip>', views.home_data, name='home_data'),

    # url(r'chat/([0-9]{5})',views.chat, name='chat'),
    # url(r'update_status/$', views.update_status, name='update_status'),
    # url(r'edit_contact/([^@]+@[^@]+\.[^@]+)', views.edit_contact, name='edit_contact'),
    # url(r'add_contact/$', views.add_contact, name='add_contact'),
    path('payment', views.payment, name='payment'),
    path('payment_ipn', views.payment_ipn, name='payment_ipn'),
    path('payment_return', views.payment_return, name='payment_return'),
    path('query', views.query, name='query'),
    path('refund', views.refund, name='refund'),
]

http_docker/kvmvdi/client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

http_docker/kvmvdi/client/forms.py
from django import forms

http_docker/kvmvdi/client/views.py
import urllib

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import logout

from django.utils.safestring import mark_safe
import json
import threading


from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from superadmin.models import MyUser, Oders, Server, Sshkeys, Flavors, Images, Ops, Networks, Snapshot
import binascii, os

from superadmin.plugin.novaclient import nova
from superadmin.plugin.get_tokens import getToken
from superadmin.plugin.neutronclient_ import neutron_

from django.utils import timezone
from kvmvdi.settings import OPS_IP, list_net_provider, DISK_HDD, DISK_SSD, \
    OPS_TOKEN_EXPIRED, OPS_ADMIN, OPS_IP, OPS_PASSWORD, OPS_PROJECT, PRICE_RAM, PRICE_VCPUS, PRICE_DISK_HDD ,PRICE_DISK_SSD, DISK_HDD, DISK_SSD
import time

import django_rq
q = django_rq.get_queue('default', default_timeout=900)
# redis_conn = django_rq.get_connection()
# worker = django_rq.get_worker()
# worker.
# worker = django_rq.get_worker('low', 'high')

# from rq import Queue
# from redis import Redis

# redis_conn = Redis()
# q = Queue(connection=redis_conn)
class EmailThread(threading.Thread):
    def __init__(self, email):
        threading.Thread.__init__(self)
        # self._stop_event = threading.Event()
        self.email = email

    def run(self):
        try:
            self.email.send()
        except Exception as e:
            print(e)
        else:
            print('Sent!')

class check_ping(threading.Thread):
    def __init__(self, host):
        threading.Thread.__init__(self)
        self._stop_event = threading.Event()
        self.host = host

    def run(self):
        # response = os.system("ping -n 1 " + self.host)
        response = os.system("ping -c 1 " + self.host)
        if response == 0:
            return True
        else:
            return False

def createServer(type_disk, flavor, image, svname, private_network, count, user, root_pass, price, o_s, cloudinit=None, sshkey=None):
    user_admin = MyUser.objects.get(username='admin')
    if user_admin.is_active and user_admin.is_adminkvm:
        if user_admin.token_id is None or user_admin.check_expired() == False:
            user_admin.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
            user_admin.token_id = getToken(ip=OPS_IP, username=OPS_ADMIN, password=OPS_PASSWORD, project_name=OPS_PROJECT, user_domain_id='default', project_domain_id='default')
            user_admin.save()
    connect_neutron = neutron_(ip=OPS_IP, token_id=user_admin.token_id, project_name=OPS_PROJECT, project_domain_id='default')
    ops = Ops.objects.get(ip=OPS_IP)
    if not user.check_expired():
        user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
        user.token_id = getToken(ip=OPS_IP, username=user.username, password=user.username,
                                    project_name=user.username, user_domain_id='default',
                                    project_domain_id='default')
        user.save()
    connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=user.username,
                    project_domain_id='default')
    fl = connect.find_flavor(id=flavor.split(',')[3])
    net = ''
    for network in list_net_provider:
        try:
            ip_net = connect.find_network(network)
        except:
            return "Xay ra loi khi check network!"
        if connect_neutron.free_ips(ip_net=ip_net) > 2:
            net = ip_net
            break
    if net == '':
        return "No IP availability!"
    try:
        im_snap = connect.find_image(image)
        im = connect.find_image(im_snap.base_image_ref)
        snapshot_id = im_snap.block_device_mapping.split('"snapshot_id": "')[1].split('", "device_name":')[0]
        try:
            volume = connect.create_volume(name=svname, size=flavor.split(',')[2], snapshot_id=snapshot_id)
        except:
            return "Xay ra loi khi tao volume snapshot!"
    except:
        im = connect.find_image(image)
        try:
            volume = connect.create_volume(name=svname, size=flavor.split(',')[2], imageRef=im.id, volume_type=type_disk)
        except:
            return "Xay ra loi khi tao volume!"
    if volume:
        check = False
        while check == False:
            if connect.check_volume(id=volume.id).status == 'error':
                return "Xay ra loi khi tao volume!"
            elif connect.check_volume(id=volume.id).status == 'available':
                volume_id = volume.id
                break
            else:
                time.sleep(2)
    else:
        return "Xay ra loi3 khi tao volume!"
    
    try:
        if o_s is not None:
            serverVM = connect.createVM(svname=svname, flavor=fl, image=im, network_id=net, private_network=private_network, volume_id=volume_id, max_count=count)
        else:
            serverVM = connect.createVM(svname=svname, flavor=fl, image=im, network_id=net, private_network=private_network, volume_id=volume_id, max_count=count, userdata=cloudinit, key_name=sshkey,)
    except:
        try:
            connect.delete_volume(volume=volume_id)
        except:
            pass
        return "Xay ra loi khi create Server!"
    user.money = str(float(user.money) - float(price))
    user.save()
    Oders.objects.create(service='cloud', price=price, created=timezone.now(), owner=user, server=svname)
    try:
        sv = Server.objects.get(name=svname)
        sv.i_d = serverVM.id
        sv.save()
    except:
        pass
    while (1):
        if connect.get_server(serverVM.id).status != 'BUILD':
            break
        else:
            time.sleep(2)
    try:
        sv = Server.objects.get(name=svname)
        sv.created = serverVM.created
        sv.save()
    except:
        pass
    mail_subject = 'Thông tin server của bạn là: '
    IP_Private = ''
    if private_network == '0':
        IP_Private = 'Khong co'
    else:
        try:
            IP_Private = connect.get_server(serverVM.id).networks[user.username][0]
        except:
            IP_Private = ''
    
    if o_s is not None:
        rootpassword = 'Cloud@intercom'
    else:
        rootpassword = root_pass

    ssh_key = ''
    if sshkey == None:
        ssh_key = 'Khong co'
    else:
        ssh_key = sshkey
    message = render_to_string('client/send_info_server.html', {
        'user': user,
        'IP_Public': connect.get_server(serverVM.id).networks[network][0],
        'IP_Private': IP_Private,
        'Key_pair': ssh_key,
        'Pass_Login': rootpassword
    })
    to_email = user.email
    email = EmailMessage(
                mail_subject, message, to=[to_email]
    )
    email.send()
    return 'Da tao xong server!'

def deleteServer(svid, svname, user):
    try:
        ops = Ops.objects.get(ip=OPS_IP)
        if not user.check_expired():
            user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
            user.token_id = getToken(ip=OPS_IP, username=user.username, password=user.username,
                                        project_name=user.username, user_domain_id='default',
                                        project_domain_id='default')
            user.save()
        connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=user.username,
                        project_domain_id='default')
        connect.delete_vm(svid=svid)
        server = Server.objects.get(name=svname, owner=user)
        server.delete()
    except:
        return "Đã có lỗi xảy ra!"
    return 'Da xoa xong'

def home(request):
    user = request.user
    if user.is_authenticated and user.is_adminkvm == False:
        return render(request, 'client/home.html',{'username': mark_safe(json.dumps(user.username)),
                                                    'money': user.money,
                                                    'count_sv': Oders.objects.filter(owner=user).count()
                                                    })
    else:
        return HttpResponseRedirect('/')

def show_instances(request, serverid):
    user = request.user
    if user.is_authenticated and user.is_adminkvm == False:
        if Ops.objects.get(ip=OPS_IP):
            thread = check_ping(host=OPS_IP)
            if thread.run():
                ops = Ops.objects.get(ip=OPS_IP)
                if not user.check_expired():
                    user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                    user.token_id = getToken(ip=OPS_IP, username=user.username, password=user.username,
                                             project_name=user.username, user_domain_id='default',
                                             project_domain_id='default')
                    user.save()
                connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=user.username, project_domain_id='default')
                sv = connect.get_server(serverid=serverid)
        if request.method == 'POST':
            if 'snapshot' in request.POST:
                ops = Ops.objects.get(ip=OPS_IP)
                if not user.check_expired():
                    user.token_expired = timezone.datetime.now() + timezone.timedelta(seconds=OPS_TOKEN_EXPIRED)
                    user.token_id = getToken(ip=OPS_IP, username=user.username, password=user.username,
                                             project_name=user.username, user_domain_id='default',
                                             project_domain_id='default')
                    user.save()
                connect = nova(ip=OPS_IP, token_id=user.token_id, project_name=user.username, project_domain_id='default')
                svid = request.POST['snapshot']
                try:

http_docker/kvmvdi/client/templates/client/home.html
{% extends "client/base.html" %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/portal/home.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block here %}
    <!--<i class="fa fa-chevron-right">-->
    <!--</i>-->
    <!--Instantces-->
{% endblock %}
{% block content %}
        {% if user.is_authenticated %}
            <div class="col-md-10 content"  id="nac2">
                <div class="col-md-10 home_content">
                    <div class="row home_billing">
                        <span>Billing</span>
                        <div class="row dashboard-card-left">
                            <p class="md-card-title">
                                Up to date credit
                            </p>
                            <div class="md-card-conten money">
                                <p>
                                    {{money}} VND
                                </p>
                            </div>
                            <div class="md-card-actions">
                                <button class="btn">
                                    <b>ADD CREDIT</b>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="dashboard-container">
                            <span>
                                Summary
                            </span>
                            <div class="row summary">
                                <table class="fl-table">
                                    <tbody>
                                        <tr>
                                            <td class="v-middle">
                                                <a ""="" href="">
                                                    {{count_sv}} instances
                                                </a>
                                            </td>
                                            <td class="v-middle">
                                                <button class="btn">
                                                    <strong>
                                                    CREATE INSTANCES
                                                    </strong>
                                                </button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="v-middle">
                                                <a ""="" href="">
                                                    No images
                                                </a>
                                            </td>
                                            <td class="v-middle">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="v-middle">
                                                <a ""="" href="">
                                                    1 volume
                                                </a>
                                            </td>
                                            <td class="v-middle">
                                                <button class="btn">
                                                    <strong>
                                                    CREATE VOLUME
                                                    </strong>
                                                </button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="v-middle">
                                                <a ""="" href="">
                                                    5 SSH keys
                                                </a>
                                            </td>
                                            <td class="v-middle">
                                                <button class="btn">
                                                    <strong>
                                                    ADD SSH KEY
                                                    </strong>
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		{% endif %}
{% endblock content %}

{% block js %}
    <script src="{% static 'js/client/home_client.js' %}"></script>
{% endblock %}

http_docker/kvmvdi/client/templates/client/networks.html
{% extends "client/base.html" %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/portal/createinstance.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block here %}
    <i class="fa fa-chevron-right">
    </i>
    Networks
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="col-md-10 col-lg-10">
    <div class="home_content" >
        <div class="web_content">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display nowrap table table-hover table-striped table-bordered list_net_client" width="100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Subnets Associated</th>
                                <th>Shared </th>
                                <th>External </th>
                                <th>Status </th>
                                <th>Admin State </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for network in networks %}
                                <tr>
                                    <td>{{network.name}}</td>
                                    <td>{{network.subnets_associated}}</td>
                                    {% if network.shared == 1 %}
                                        <td>Yes</td>
                                    {% else%}
                                        <td>No</td>
                                    {% endif%}
                                    {% if network.external == 1 %}
                                        <td>Yes</td>
                                    {% else%}
                                        <td>No</td>
                                    {% endif%}
                                    <td>{{network.status}}</td>
                                    {% if network.admin_state_up == 1 %}
                                        <td>UP</td>
                                    {% else%}
                                        <td>DOWN</td>
                                    {% endif%}
                                </tr>
                            {% endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</div>


{% endif %}
{% endblock content %}
{% block js %}
<script src="{% static 'js/base-js/datatables.min.js' %}"></script>
{% endblock %}

http_docker/kvmvdi/client/templates/client/payment.html
{% extends "client/base.html" %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/portal/home.css' %}" rel="stylesheet" type="text/css">
    <link href="https://pay.vnpay.vn/lib/vnpay/vnpay.css" rel="stylesheet"/>

{% endblock %}
{% block here %}
    <i class="fa fa-chevron-right">
    </i>
    Recharge
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="col-md-10 col-lg-10">
    <div class="home_content" >
        <div class="web_content">
            <div class="card-body">
                <div class="table-responsive">
                    <form action="{% url 'superadmin:payment' %}" id="create_form" method="post">
                        <div class="form-group">
                            <label for="language">Loại hàng hóa </label>
                            <select name="order_type" id="order_type" class="form-control">
                                <option value="topup">Nạp tiền điện thoại</option>
                                <option value="billpayment">Thanh toán hóa đơn</option>
                                <option value="fashion">Thời trang</option>
                                <option value="other">Khác - Xem thêm tại VNPAY</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="order_id">Mã hóa đơn</label>
                            <input class="form-control" id="order_id"
                                   name="order_id" type="text" value="{% now 'YmdHis' %}"/>
                        </div>
                        <div class="form-group">
                            <label for="amount">Số tiền</label>
                            <input class="form-control" id="amount"
                                   name="amount" type="number" value="10000"/>
                        </div>
                        <div class="form-group">
                            <label for="order_desc">Nội dung thanh toán</label>
                            <textarea class="form-control" cols="20" id="order_desc" name="order_desc" rows="2">Thanh toan don hang thoi gian: {% now "Y-m-d H:i:s" %}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="bank_code">Ngân hàng</label>
                            <select name="bank_code" id="bank_code" class="form-control">
                                <option value="">Không chọn</option>
                                <option value="NCB"> Ngan hang NCB</option>
                                <option value="AGRIBANK"> Ngan hang Agribank</option>
                                <option value="SCB"> Ngan hang SCB</option>
                                <option value="SACOMBANK">Ngan hang SacomBank</option>
                                <option value="EXIMBANK"> Ngan hang EximBank</option>
                                <option value="MSBANK"> Ngan hang MSBANK</option>
                                <option value="NAMABANK"> Ngan hang NamABank</option>
                                <option value="VNMART"> Vi dien tu VnMart</option>
                                <option value="VIETINBANK">Ngan hang Vietinbank</option>
                                <option value="VIETCOMBANK"> Ngan hang VCB</option>
                                <option value="HDBANK">Ngan hang HDBank</option>
                                <option value="DONGABANK"> Ngan hang Dong A</option>
                                <option value="TPBANK"> Ngân hàng TPBank</option>
                                <option value="OJB"> Ngân hàng OceanBank</option>
                                <option value="BIDV"> Ngân hàng BIDV</option>
                                <option value="TECHCOMBANK"> Ngân hàng Techcombank</option>
                                <option value="VPBANK"> Ngan hang VPBank</option>
                                <option value="MBBANK"> Ngan hang MBBank</option>
                                <option value="ACB"> Ngan hang ACB</option>
                                <option value="OCB"> Ngan hang OCB</option>
                                <option value="IVB"> Ngan hang IVB</option>
                                <option value="VISA"> Thanh toan qua VISA/MASTER</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="language">Ngôn ngữ</label>
                            <select name="language" id="language" class="form-control">
                                <option value="vn">Tiếng Việt</option>
                                <option value="en">English</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary" id="btnPopup">Thanh toán Popup</button>
                        <!--<button type="submit" class="btn btn-default">Thanh toán Redirect</button>-->
                        {% csrf_token %}
                        <div class="form-group"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<script src="https://pay.vnpay.vn/lib/vnpay/vnpay.js"></script>
<script type="text/javascript">
    $("#btnPopup").click(function () {
        var postData = $("#create_form").serialize();
        console.log(postData);
        var submitUrl = $("#create_form").attr("action");
        $.ajax({
            type: "POST",
            url: submitUrl,
            data: postData,
            dataType: 'JSON',
            success: function (x) {
                if (x.code === '00') {
                    if (window.vnpay) {
                        vnpay.open({width: 768, height: 600, url: x.data});
                    }
                    else {
                        location.href = x.data;
                    }
                    return false;
                } else {
                    alert(x.Message);
                }
            }
        });
        return false;
    });
</script>
{% endif %}
{% endblock content %}

{% block js %}
    <script src="{% static 'js/client/home_client.js' %}"></script>
{% endblock %}

http_docker/kvmvdi/client/templates/client/query.html
{% extends "client/base.html" %}
{% block here %}
    <i class="fa fa-chevron-right">
    </i>
    Query
{% endblock %}

{% block content %}
<div class="col-md-10 col-lg-10">
    <div class="home_content" >
        <div class="web_content">
            <h3>{{ title }}</h3>
            <div class="table-responsive">
                <form action="{% url 'superadmin:query' %}" id="create_form" method="post">

                    <div class="form-group">
                        <label for="order_id">Mã hóa đơn</label>
                        <input class="form-control" id="order_id"
                               name="order_id" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="order_id">Thời gian thanh toán</label>
                        <input class="form-control" id="trans_date"
                               name="trans_date" type="text"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Query</button>
                    </div>

                    {% csrf_token %}
                </form>
                {% if data %}
                    {% for key,val in data.items %}
                     <div class="form-group">
                        <label>{{ key }}: {{ val }}</label>
                    </div>
                    {% endfor %}

                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

http_docker/kvmvdi/client/templates/client/refund.html
{% extends "client/base.html" %}
{% block here %}
    <i class="fa fa-chevron-right">
    </i>
    Refund
{% endblock %}
{% block content %}
<div class="col-md-10 col-lg-10">
    <div class="home_content" >
        <div class="web_content">
            <h3>{{ title }}</h3>
            <div class="table-responsive">
                <form action="{% url 'superadmin:query' %}" id="create_form" method="post">

                    <div class="form-group">
                        <label for="order_id">Mã hóa đơn</label>
                        <input class="form-control" id="order_id"
                               name="order_id" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="order_id">Số tiền hoàn trả</label>
                        <input class="form-control" id="amount"
                               name="amount" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="order_id">Nội dung/lý do hoàn trả</label>
                        <input class="form-control" id="order_desc"
                               name="order_desc" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="order_id">Thời gian Thanh toán</label>
                        <input class="form-control" id="trans_date"
                               name="trans_date" type="text"/>
                    </div>
                    <div class="form-group">
                        <label for="order_id">Ngày GD</label>
                        <input class="form-control" id="trans_date"
                               name="trans_date" type="text"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Query</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

http_docker/kvmvdi/client/templates/client/send_info_key.html
{% autoescape off %}
Xin chào {{ user.fullname }},
Thông tin key pair {{key_name}} của bạn là:
Public key:
{{public_key}}
{% endautoescape %}